# Uncomment the next line to define a global platform for your project

 platform :ios, '8.0'
use_frameworks!
target 'U-CITY' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'Firebase/AdMob'
  pod 'Firebase/Messaging'
  pod 'Firebase/Database'
  pod 'Firebase/Storage'
  pod 'FBSDKLoginKit'
  pod 'MaterialComponents/AppBar'
  pod 'GoogleSignIn'
  pod 'Google'
  pod 'LineSDK'
  pod 'Kingfisher', '~> 4.0'
  # Pods for U-CITY


end
